server:
  port: ${SERVER_PORT:8092}
spring:
  profiles:
    active: ${SPRING_ACTIVE_PROFILE:local}
  application:
    name: joinews
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
  flyway:
    baseline-on-migrate: true
    out-of-order: true
    schemas: joinews
    locations: classpath:/db/migration/common/ddl, classpath:/db/migration/common/dml, classpath:/db/migration/${SPRING_ACTIVE_PROFILE:local}/ddl, classpath:/db/migration/${SPRING_ACTIVE_PROFILE:local}/dml
    clean-disabled: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/local?currentSchema=joinews}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:p@ssw0rd}
    hikari:
      maximum-pool-size: 32