name: Springboot CI
on:
  push:
    branches: ["master"]
    paths-ignore:
      - "web/**"

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Grant Permissions to gradlew
      run: chmod +x gradlew
    - name: Test
      run: ./gradlew test --tests "*"


  build-image-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Grant Permissions to gradlew
        run: chmod +x gradlew
      - name: Build
        run: |
          ./gradlew build
          cp ./build/libs/joi-news-1.0-SNAPSHOT.jar ./
      -
        name: check 
        run: pwd
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        run: |
          docker build -t dingyi2000/backend .
          docker push dingyi2000/backend


  # deploy:
  #   needs: build-image-push
  #   runs-on: self-hosted
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Public IP
  #       id: ip
  #       uses: haythem/public-ip@v1.3
  #     - name: ssh to web1 to run web
  #       run: |
  #         ssh -i /Users/dingyi.tian/Desktop/sre-learning-by-doing/slbd-infra/config/web1 ubuntu@${{ secrets.WEB1_HOST }} "docker stop web;docker rm web;docker run -d --name=web -p 3000:3000 -e REACT_APP_API_BASE_URL:=http://localhost:8092 dingyi2000/web"

  #     - name: ssh to web2 to run web
  #       run: |
  #         ssh -i /Users/dingyi.tian/Desktop/sre-learning-by-doing/slbd-infra/config/web2 ubuntu@${{ secrets.WEB2_HOST }} "docker stop web;docker rm web;docker run -d --name=web -p 3000:3000 -e REACT_APP_API_BASE_URL:=http://localhost:8092 dingyi2000/web"





